"""
RSI-EMA Strategy - Winner strategy implementation for live trading.

Uses EMA(10/58) regime filter with RSI(27/58) entry/exit signals.
Compatible with both backtester (DataFrame signals) and live trading (single Signal).
"""

import json
import logging
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Any

import numpy as np
import pandas as pd

from lib.trading.indicators import ema, rsi, atr

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    timestamp: str
    symbol: str
    action: str  # 'entry_long', 'exit', 'hold'
    confidence: float  # 0.0 - 1.0
    indicators: Dict[str, float]
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class RSIEMAStrategy:
    """
    RSI-EMA momentum strategy.

    Entry: RSI < rsi_entry AND EMA_fast > EMA_slow (uptrend)
    Exit:  RSI > rsi_exit OR EMA_fast < EMA_slow (regime change)

    Default parameters from config/dex_winner.json:
        EMA fast=10, slow=58
        RSI entry=27, exit=58
        TP=7.23%, SL=4.23%, ATR cap=3%
    """

    def __init__(
        self,
        ema_fast: int = 10,
        ema_slow: int = 58,
        rsi_period: int = 14,
        rsi_entry: float = 27.0,
        rsi_exit: float = 58.0,
        take_profit: float = 0.0723,
        stop_loss: float = 0.0423,
        atr_period: int = 14,
        atr_cap_pct: float = 0.03,
    ):
        self.ema_fast = ema_fast
        self.ema_slow = ema_slow
        self.rsi_period = rsi_period
        self.rsi_entry = rsi_entry
        self.rsi_exit = rsi_exit
        self.take_profit = take_profit
        self.stop_loss = stop_loss
        self.atr_period = atr_period
        self.atr_cap_pct = atr_cap_pct

    @classmethod
    def from_winner_config(cls, path: str = "config/dex_winner.json") -> "RSIEMAStrategy":
        """Load strategy from winner config file."""
        config_path = Path(path)
        if not config_path.exists():
            logger.warning(f"Winner config not found at {path}, using defaults")
            return cls()

        with open(config_path) as f:
            cfg = json.load(f)

        regime = cfg.get("regime", {})
        entry = cfg.get("entry", {})
        exit_ = cfg.get("exit", {})
        risk = cfg.get("risk", {})

        return cls(
            ema_fast=regime.get("fast", 10),
            ema_slow=regime.get("slow", 58),
            rsi_entry=entry.get("threshold", 27),
            rsi_exit=exit_.get("threshold", 58),
            take_profit=risk.get("tp", 0.0723),
            stop_loss=risk.get("sl", 0.0423),
            atr_cap_pct=risk.get("atr_cap_pct", 0.03),
        )

    @classmethod
    def from_params(cls, params: Dict[str, Any]) -> "RSIEMAStrategy":
        """Create strategy from a flat parameter dict (used by research orchestrator)."""
        return cls(
            ema_fast=params.get("ema_fast", 10),
            ema_slow=params.get("ema_slow", 58),
            rsi_period=params.get("rsi_period", 14),
            rsi_entry=params.get("rsi_entry", 27),
            rsi_exit=params.get("rsi_exit", 58),
            take_profit=params.get("take_profit", 0.0723),
            stop_loss=params.get("stop_loss", 0.0423),
            atr_cap_pct=params.get("atr_cap_pct", 0.03),
        )

    def to_params(self) -> Dict[str, Any]:
        """Serialize strategy to parameter dict."""
        return {
            "ema_fast": self.ema_fast,
            "ema_slow": self.ema_slow,
            "rsi_period": self.rsi_period,
            "rsi_entry": self.rsi_entry,
            "rsi_exit": self.rsi_exit,
            "take_profit": self.take_profit,
            "stop_loss": self.stop_loss,
            "atr_period": self.atr_period,
            "atr_cap_pct": self.atr_cap_pct,
        }

    # ── DataFrame-based signals (backtester compatible) ─────────────

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add indicator columns to a DataFrame.

        Args:
            df: OHLCV DataFrame with columns [open, high, low, close, volume]

        Returns:
            DataFrame with added indicator columns.
        """
        out = df.copy()
        close = out["close"]
        high = out["high"]
        low = out["low"]

        out["ema_fast"] = ema(close, self.ema_fast)
        out["ema_slow"] = ema(close, self.ema_slow)
        out["rsi"] = rsi(close, self.rsi_period)
        out["atr"] = atr(high, low, close, self.atr_period)

        # Regime: uptrend when fast EMA > slow EMA
        out["uptrend"] = out["ema_fast"] > out["ema_slow"]

        return out

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        """Generate entry/exit boolean columns for backtesting.

        Returns DataFrame with 'entries' and 'exits' boolean columns,
        compatible with backtester_vbt.run_backtest().
        """
        out = self.calculate_indicators(df)

        # Entry: RSI below threshold AND uptrend regime
        out["entries"] = (out["rsi"] < self.rsi_entry) & out["uptrend"]

        # Exit: RSI above threshold OR regime change to downtrend
        out["exits"] = (out["rsi"] > self.rsi_exit) | (~out["uptrend"])

        # Fill NaN from rolling calcs
        out["entries"] = out["entries"].fillna(False)
        out["exits"] = out["exits"].fillna(False)

        return out

    # ── Single-bar signal (live trading compatible) ─────────────────

    def generate_signal(
        self,
        features: Dict[str, Any],
        symbol: str = "BTC/USDC",
    ) -> Signal:
        """Generate a single Signal from FeatureExtractor output.

        Args:
            features: Output dict from FeatureExtractor.extract()
            symbol: Trading pair

        Returns:
            Signal dataclass with action and metadata.
        """
        now = datetime.now(timezone.utc).isoformat()

        feat = features.get("features", {})
        trend = feat.get("trend", {})
        momentum = feat.get("momentum", {})
        volatility = feat.get("volatility", {})
        price_info = feat.get("price", {})

        rsi_val = momentum.get("rsi_14", 50.0)
        ema_f = trend.get("ema_10", 0.0)
        ema_s = trend.get("ema_58", 0.0)
        atr_val = volatility.get("atr_14", 0.0)
        close = price_info.get("close", 0.0)

        uptrend = ema_f > ema_s
        indicators = {
            "rsi": rsi_val,
            "ema_fast": ema_f,
            "ema_slow": ema_s,
            "atr": atr_val,
            "close": close,
        }

        # Entry condition
        if rsi_val < self.rsi_entry and uptrend:
            # Confidence scales with how oversold RSI is
            base_confidence = 0.7
            rsi_bonus = min(0.2, (self.rsi_entry - rsi_val) / self.rsi_entry * 0.3)
            volume_bonus = 0.1 if feat.get("volume", {}).get("volume_confirmation", False) else 0.0
            confidence = min(1.0, base_confidence + rsi_bonus + volume_bonus)

            sl_price = close * (1 - self.stop_loss) if close else None
            tp_price = close * (1 + self.take_profit) if close else None

            return Signal(
                timestamp=now,
                symbol=symbol,
                action="entry_long",
                confidence=round(confidence, 3),
                indicators=indicators,
                stop_loss=sl_price,
                take_profit=tp_price,
                reason=f"RSI {rsi_val:.1f} < {self.rsi_entry} in uptrend",
            )

        # Exit condition
        if rsi_val > self.rsi_exit or not uptrend:
            reasons = []
            if rsi_val > self.rsi_exit:
                reasons.append(f"RSI {rsi_val:.1f} > {self.rsi_exit}")
            if not uptrend:
                reasons.append("regime change to downtrend")
            confidence = 0.9 if rsi_val > 70 else 0.7

            return Signal(
                timestamp=now,
                symbol=symbol,
                action="exit",
                confidence=round(confidence, 3),
                indicators=indicators,
                reason="; ".join(reasons),
            )

        # No signal - hold
        return Signal(
            timestamp=now,
            symbol=symbol,
            action="hold",
            confidence=0.0,
            indicators=indicators,
            reason="No entry/exit conditions met",
        )

    def __repr__(self) -> str:
        return (
            f"RSIEMAStrategy(ema={self.ema_fast}/{self.ema_slow}, "
            f"rsi={self.rsi_entry}/{self.rsi_exit}, "
            f"tp={self.take_profit:.2%}, sl={self.stop_loss:.2%})"
        )
