metadata:
  asset: $MICHI
  optimization_date: '2025-09-06T10:14:11.241700'
  optimization_type: gepa_prompt_evolution
  session_id: '20250906_101315'
optimized_prompts:
  generate_strategy.predict: Generate trading strategy based on market conditions
  reason_metrics.predict: Reason about strategy performance metrics
usage_instructions:
  metric_reasoning: Use for predicting strategy performance with reasoning
  strategy_generation: Use for generating DEX trading strategies
